<#
.SYNOPSIS
Provision Dataverse tables and columns using the Web API.

.DESCRIPTION
This script uses the Dataverse Web API to create tables and columns for the PAP Checklist application.
It uses 'pac auth token' to retrieve the access token, so ensure you are authenticated via 'pac auth create'.

.EXAMPLE
.\provision-dataverse-api.ps1 -EnvironmentUrl "https://your-org.crm.dynamics.com" --PublisherPrefix "pap"
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$EnvironmentUrl,

    [string]$PublisherPrefix = "pap"
)

# Remove trailing slash
$EnvironmentUrl = $EnvironmentUrl.TrimEnd('/')
$ApiUrl = "$EnvironmentUrl/api/data/v9.2"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "PAP Checklist - Dataverse Provisioning" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Target Environment: $EnvironmentUrl" -ForegroundColor Yellow
Write-Host "Publisher Prefix:   $PublisherPrefix" -ForegroundColor Yellow

# ============================================
# 1. Authentication (Using Azure CLI)
# ============================================

Write-Host "`n[1/4] Authenticating..." -ForegroundColor Cyan

# Use Azure CLI to get access token for Dataverse
# This is more reliable than parsing pac auth token output
try {
    # Check if az is installed
    $azCheck = Get-Command az -ErrorAction SilentlyContinue
    if (-not $azCheck) {
        throw "Azure CLI ('az') is not installed. Install from: https://aka.ms/installazurecli"
    }

    Write-Host "Retrieving access token from Azure CLI..." -ForegroundColor Gray
    
    # Get token for Dataverse resource
    $tokenJson = az account get-access-token --resource "$EnvironmentUrl" 2>&1
    
    # Check if az login is needed
    if ($tokenJson -match "Please run 'az login'") {
        Write-Host "Azure CLI not logged in. Please run: az login --allow-no-subscriptions" -ForegroundColor Red
        exit 1
    }
    
    # Parse JSON response
    $tokenObj = $tokenJson | ConvertFrom-Json
    $accessToken = $tokenObj.accessToken

    if ([string]::IsNullOrWhiteSpace($accessToken)) {
        Write-Host "Could not retrieve token. Ensure you are logged in to Azure CLI." -ForegroundColor Red
        Write-Host "Run: az login --allow-no-subscriptions" -ForegroundColor Yellow
        exit 1
    }
    
    Write-Host "  ✓ Token retrieved (length: $($accessToken.Length) chars)" -ForegroundColor Green

} catch {
    Write-Host "  ✗ Error retrieving token: $_" -ForegroundColor Red
    Write-Host ""
    Write-Host "To fix, run these commands in your terminal:" -ForegroundColor Yellow
    Write-Host "  1. az login --allow-no-subscriptions" -ForegroundColor White
    Write-Host "  2. Then re-run this script" -ForegroundColor White
    exit 1
}

$headers = @{
    "Authorization" = "Bearer $accessToken"
    "Content-Type"  = "application/json"
    "OData-MaxVersion" = "4.0"
    "OData-Version" = "4.0"
}

# ============================================
# 2. Helper Functions
# ============================================

function Create-Table {
    param($SchemaName, $DisplayName, $PluralName, $Description, $PrimaryColumnName)
    
    $fullSchemaName = "${PublisherPrefix}_${SchemaName}"
    $fullPrimaryName = "${PublisherPrefix}_${PrimaryColumnName}"

    Write-Host "  Creating Table: $DisplayName ($fullSchemaName)..." -NoNewline
    
    # Note: EntitySet is read-only and auto-generated by Dataverse, do not specify it
    $body = @{
        "@odata.type" = "Microsoft.Dynamics.CRM.EntityMetadata"
        SchemaName = $fullSchemaName
        DisplayName = @{ 
            "@odata.type" = "Microsoft.Dynamics.CRM.Label"
            LocalizedLabels = @(
                @{ 
                    "@odata.type" = "Microsoft.Dynamics.CRM.LocalizedLabel"
                    Label = $DisplayName
                    LanguageCode = 1033 
                }
            ) 
        }
        DisplayCollectionName = @{ 
            "@odata.type" = "Microsoft.Dynamics.CRM.Label"
            LocalizedLabels = @(
                @{ 
                    "@odata.type" = "Microsoft.Dynamics.CRM.LocalizedLabel"
                    Label = $PluralName
                    LanguageCode = 1033 
                }
            ) 
        }
        Description = @{ 
            "@odata.type" = "Microsoft.Dynamics.CRM.Label"
            LocalizedLabels = @(
                @{ 
                    "@odata.type" = "Microsoft.Dynamics.CRM.LocalizedLabel"
                    Label = $Description
                    LanguageCode = 1033 
                }
            ) 
        }
        OwnershipType = "UserOwned"
        HasActivities = $false
        HasNotes = $false
        Attributes = @(
            @{
                "@odata.type" = "Microsoft.Dynamics.CRM.StringAttributeMetadata"
                SchemaName = $fullPrimaryName
                AttributeType = "String"
                FormatName = @{ Value = "Text" }
                DisplayName = @{
                    "@odata.type" = "Microsoft.Dynamics.CRM.Label" 
                    LocalizedLabels = @(
                        @{ 
                            "@odata.type" = "Microsoft.Dynamics.CRM.LocalizedLabel"
                            Label = "Name"
                            LanguageCode = 1033 
                        }
                    ) 
                }
                MaxLength = 100
                IsPrimaryName = $true
            }
        )
    }

    try {
        $jsonBody = $body | ConvertTo-Json -Depth 10
        $response = Invoke-RestMethod -Method Post -Uri "$ApiUrl/EntityDefinitions" -Headers $headers -Body $jsonBody -SkipHttpErrorCheck -StatusCodeVariable "sc"
        
        if ($sc -eq 204 -or $sc -eq 201) {
            Write-Host " Success" -ForegroundColor Green
            return $true
        } elseif ($sc -eq 409) {
            Write-Host " Exists (Skipping)" -ForegroundColor Yellow
            return $true # Treat as success
        } else {
            Write-Host " Failed ($sc)" -ForegroundColor Red
            Write-Host ($response | ConvertTo-Json -Depth 3)
            return $false
        }
    } catch {
        Write-Host " Error: $_" -ForegroundColor Red
        return $false
    }
}

function Create-Column {
    param($TableName, $SchemaName, $DisplayName, $Type, $Required=$false, $MaxLength=100, $Options=$null, $LookupTarget=$null, $MemoMaxLength=1048576)  # 1MB max for all multiline text
    
    $tableSchemaName = "${PublisherPrefix}_${TableName}"
    $colSchemaName = "${PublisherPrefix}_${SchemaName}"
    
    Write-Host "    Column: $DisplayName ($colSchemaName)..." -NoNewline

    # Check if column exists
    try {
        Invoke-RestMethod -Method Get -Uri "$ApiUrl/EntityDefinitions(LogicalName='$tableSchemaName')/Attributes(LogicalName='$colSchemaName')" -Headers $headers -SkipHttpErrorCheck -StatusCodeVariable "checkSc" | Out-Null
        if ($checkSc -eq 200) {
            Write-Host " Exists" -ForegroundColor Gray
            return
        }
    } catch {}

    $attributeBody = @{
        SchemaName = $colSchemaName
        DisplayName = @{ 
            "@odata.type" = "Microsoft.Dynamics.CRM.Label"
            LocalizedLabels = @(
                @{ 
                    "@odata.type" = "Microsoft.Dynamics.CRM.LocalizedLabel"
                    Label = $DisplayName
                    LanguageCode = 1033 
                }
            ) 
        }
        RequiredLevel = @{ Value = if($Required) { "ApplicationRequired" } else { "None" } }
    }

    if ($Type -eq "String") {
        $attributeBody["@odata.type"] = "Microsoft.Dynamics.CRM.StringAttributeMetadata"
        $attributeBody["FormatName"] =  @{ Value = "Text" }
        $attributeBody["MaxLength"] = $MaxLength
    }
    elseif ($Type -eq "MultilineText") {
        $attributeBody["@odata.type"] = "Microsoft.Dynamics.CRM.MemoAttributeMetadata"
        $attributeBody["Format"] = "TextArea"
        $attributeBody["MaxLength"] = $MemoMaxLength
    }
    elseif ($Type -eq "Integer") {
        $attributeBody["@odata.type"] = "Microsoft.Dynamics.CRM.IntegerAttributeMetadata"
        $attributeBody["Format"] = "None"
    }
    elseif ($Type -eq "Boolean") {
        $attributeBody["@odata.type"] = "Microsoft.Dynamics.CRM.BooleanAttributeMetadata"
        $attributeBody["OptionSet"] = @{
            TrueOption = @{ 
                Value = 1
                Label = @{ 
                    "@odata.type" = "Microsoft.Dynamics.CRM.Label"
                    LocalizedLabels = @(
                        @{ 
                            "@odata.type" = "Microsoft.Dynamics.CRM.LocalizedLabel"
                            Label = "Yes"
                            LanguageCode = 1033 
                        }
                    ) 
                } 
            }
            FalseOption = @{ 
                Value = 0
                Label = @{ 
                    "@odata.type" = "Microsoft.Dynamics.CRM.Label"
                    LocalizedLabels = @(
                        @{ 
                            "@odata.type" = "Microsoft.Dynamics.CRM.LocalizedLabel"
                            Label = "No"
                            LanguageCode = 1033 
                        }
                    ) 
                } 
            }
        }
    }
    elseif ($Type -eq "Choice") {
        $attributeBody["@odata.type"] = "Microsoft.Dynamics.CRM.PicklistAttributeMetadata"
        $optionsList = @()
        $val = 1
        foreach ($opt in $Options) {
            $optionsList += @{ 
                Value = $val
                Label = @{ 
                    "@odata.type" = "Microsoft.Dynamics.CRM.Label"
                    LocalizedLabels = @(
                        @{ 
                            "@odata.type" = "Microsoft.Dynamics.CRM.LocalizedLabel"
                            Label = $opt
                            LanguageCode = 1033 
                        }
                    ) 
                } 
            }
            $val++
        }
        $attributeBody["OptionSet"] = @{
            IsGlobal = $false
            Options = $optionsList
        }
    }
    elseif ($Type -eq "Lookup") {
        $attributeBody["@odata.type"] = "Microsoft.Dynamics.CRM.LookupAttributeMetadata"
        Write-Host " Use Create-Lookup instead" -ForegroundColor Yellow
        return
    }

    try {
        $jsonBody = $attributeBody | ConvertTo-Json -Depth 10
        $response = Invoke-RestMethod -Method Post -Uri "$ApiUrl/EntityDefinitions(LogicalName='$tableSchemaName')/Attributes" -Headers $headers -Body $jsonBody -SkipHttpErrorCheck -StatusCodeVariable "sc"
        if ($sc -eq 204) { Write-Host " Created" -ForegroundColor Green }
        else { 
            Write-Host " Failed ($sc)" -ForegroundColor Red 
            Write-Host ($response | ConvertTo-Json -Depth 3)
        }
    } catch {
        Write-Host " Error: $_" -ForegroundColor Red
    }
}

function Create-Lookup {
    param($Table, $TargetTable, $SchemaName, $DisplayName)
    
    $tableSchema = "${PublisherPrefix}_${Table}"
    $targetSchema = if ($TargetTable -eq "systemuser") { "systemuser" } else { "${PublisherPrefix}_${TargetTable}" }
    $colSchema = "${PublisherPrefix}_${SchemaName}"
    $relSchema = "${tableSchema}_${targetSchema}_${colSchema}"

    Write-Host "    Lookup: $DisplayName ($colSchema) -> $TargetTable..." -NoNewline

    $body = @{
        "@odata.type" = "Microsoft.Dynamics.CRM.OneToManyRelationshipMetadata"
        SchemaName = $relSchema
        ReferencedEntity = $targetSchema
        ReferencingEntity = $tableSchema
        Lookup = @{
            "@odata.type" = "Microsoft.Dynamics.CRM.LookupAttributeMetadata"
            SchemaName = $colSchema
            DisplayName = @{ 
                "@odata.type" = "Microsoft.Dynamics.CRM.Label"
                LocalizedLabels = @(
                    @{ 
                        "@odata.type" = "Microsoft.Dynamics.CRM.LocalizedLabel"
                        Label = $DisplayName
                        LanguageCode = 1033 
                    }
                ) 
            }
            RequiredLevel = @{ Value = "None" }
        }
        CascadeConfiguration = @{
            Assign = "NoCascade"
            Delete = "RemoveLink"
            Merge = "NoCascade"
            Reparent = "NoCascade"
            Share = "NoCascade"
            Unshare = "NoCascade"
        }
    }
    
    try {
        $jsonBody = $body | ConvertTo-Json -Depth 10
        $response = Invoke-RestMethod -Method Post -Uri "$ApiUrl/RelationshipDefinitions" -Headers $headers -Body $jsonBody -SkipHttpErrorCheck -StatusCodeVariable "sc"
        if ($sc -eq 204) { Write-Host " Created" -ForegroundColor Green }
        elseif ($sc -eq 409) { Write-Host " Exists" -ForegroundColor Gray }
        else { 
            Write-Host " Failed ($sc)" -ForegroundColor Red 
            Write-Host ($response | ConvertTo-Json -Depth 3) 
        }
    } catch {
        Write-Host " Error: $_" -ForegroundColor Red
    }
}

# ============================================
# 3. Create Tables
# ============================================

Write-Host "`n[2/4] Creating Tables..." -ForegroundColor Cyan

# 0. Job (New for Dev Env)
#Create-Table -SchemaName "job" -DisplayName "Job" -PluralName "Jobs" -Description "Jobs/Projects" -PrimaryColumnName "name"

# 1. Checklist
Create-Table -SchemaName "checklist" -DisplayName "Checklist" -PluralName "Checklists" -Description "PAP Estimator Checklists" -PrimaryColumnName "name"

# 2. Workgroup
Create-Table -SchemaName "workgroup" -DisplayName "Workgroup" -PluralName "Workgroups" -Description "Checklist Workgroups" -PrimaryColumnName "name"

# 3. Checklist Row
Create-Table -SchemaName "checklistrow" -DisplayName "Checklist Row" -PluralName "Checklist Rows" -Description "Individual checklist items" -PrimaryColumnName "description_primary"
# Note: Primary column for row is description, but we'll specific description field separately for multiline

# 4. Revision
Create-Table -SchemaName "revision" -DisplayName "Revision" -PluralName "Revisions" -Description "Checklist Snapshots" -PrimaryColumnName "name" # "Revision X"

# 5. Comment
Create-Table -SchemaName "comment" -DisplayName "Comment" -PluralName "Comments" -Description "User comments" -PrimaryColumnName "id_name"

# 6. Default Workgroup (Template)
Create-Table -SchemaName "defaultworkgroup" -DisplayName "Default Workgroup" -PluralName "Default Workgroups" -Description "Template Workgroups" -PrimaryColumnName "name"

# 7. Default Row (Template)
Create-Table -SchemaName "defaultrow" -DisplayName "Default Row" -PluralName "Default Rows" -Description "Template Rows" -PrimaryColumnName "description_primary"

# ============================================
# 4. Create Columns
# ============================================

Write-Host "`n[3/4] Creating Columns..." -ForegroundColor Cyan

# --- Job ---
# Create-Column -TableName "job" -SchemaName "number" -DisplayName "Job Number" -Type "String"
# Create-Column -TableName "job" -SchemaName "clientname" -DisplayName "Client Name" -Type "String"
# Create-Column -TableName "job" -SchemaName "address" -DisplayName "Site Address" -Type "MultilineText"

# --- Checklist ---
Create-Column -TableName "checklist" -SchemaName "currentrevisionnumber" -DisplayName "Current Revision" -Type "Integer"
Create-Column -TableName "checklist" -SchemaName "status" -DisplayName "Status" -Type "Choice" -Options @("Draft", "In Review", "Final")
Create-Column -TableName "checklist" -SchemaName "clientcorrespondence" -DisplayName "Client Correspondence" -Type "MultilineText"
Create-Column -TableName "checklist" -SchemaName "estimatetype" -DisplayName "Estimate Type" -Type "MultilineText"
Create-Column -TableName "checklist" -SchemaName "commonnotes" -DisplayName "Common Notes" -Type "MultilineText"

# --- Workgroup ---
Create-Column -TableName "workgroup" -SchemaName "number" -DisplayName "Number" -Type "String" # String to handle "20.28"
Create-Column -TableName "workgroup" -SchemaName "order" -DisplayName "Order" -Type "Integer"
Create-Column -TableName "workgroup" -SchemaName "summarynotes" -DisplayName "Summary Notes" -Type "MultilineText"
Create-Column -TableName "workgroup" -SchemaName "isdefault" -DisplayName "Is Default" -Type "Boolean"
Create-Column -TableName "workgroup" -SchemaName "iscustom" -DisplayName "Is Custom" -Type "Boolean"

# --- Checklist Row ---
Create-Column -TableName "checklistrow" -SchemaName "description" -DisplayName "Description" -Type "MultilineText"
Create-Column -TableName "checklistrow" -SchemaName "answer" -DisplayName "Answer" -Type "Choice" -Options @("YES", "NO", "BLANK", "PS", "PC", "SUB", "OTS")
Create-Column -TableName "checklistrow" -SchemaName "notes" -DisplayName "Notes" -Type "MultilineText"
Create-Column -TableName "checklistrow" -SchemaName "markedforreview" -DisplayName "Marked for Review" -Type "Boolean"
Create-Column -TableName "checklistrow" -SchemaName "order" -DisplayName "Order" -Type "Integer"
Create-Column -TableName "checklistrow" -SchemaName "isdefault" -DisplayName "Is Default" -Type "Boolean"
Create-Column -TableName "checklistrow" -SchemaName "iscustom" -DisplayName "Is Custom" -Type "Boolean"

# --- Revision ---
Create-Column -TableName "revision" -SchemaName "summary" -DisplayName "Summary" -Type "MultilineText"
Create-Column -TableName "revision" -SchemaName "number" -DisplayName "Revision Number" -Type "Integer"
Create-Column -TableName "revision" -SchemaName "snapshotjson" -DisplayName "Snapshot JSON" -Type "MultilineText"

# --- Comment ---
Create-Column -TableName "comment" -SchemaName "text" -DisplayName "Text" -Type "MultilineText"
Create-Column -TableName "comment" -SchemaName "author" -DisplayName "Author Name" -Type "String"

# --- Default Workgroup ---
Create-Column -TableName "defaultworkgroup" -SchemaName "number" -DisplayName "Number" -Type "String"
Create-Column -TableName "defaultworkgroup" -SchemaName "order" -DisplayName "Order" -Type "Integer"
Create-Column -TableName "defaultworkgroup" -SchemaName "isactive" -DisplayName "Is Active" -Type "Boolean"

# --- Default Row ---
Create-Column -TableName "defaultrow" -SchemaName "description" -DisplayName "Description" -Type "MultilineText"
Create-Column -TableName "defaultrow" -SchemaName "order" -DisplayName "Order" -Type "Integer"
Create-Column -TableName "defaultrow" -SchemaName "isactive" -DisplayName "Is Active" -Type "Boolean"

# ============================================
# 5. Create Relationships (Lookups)
# ============================================

Write-Host "`n[4/4] Creating Relationships..." -ForegroundColor Cyan

# Checklist -> Job (Assuming pap_job exists, otherwise creation will fail)
# If pap_job doesn't exist, you might need to create it or prompt user
Create-Lookup -Table "checklist" -TargetTable "job" -SchemaName "jobid" -DisplayName "Job"

# Workgroup -> Checklist
Create-Lookup -Table "workgroup" -TargetTable "checklist" -SchemaName "checklistid" -DisplayName "Checklist"

# Row -> Workgroup
Create-Lookup -Table "checklistrow" -TargetTable "workgroup" -SchemaName "workgroupid" -DisplayName "Workgroup"

# Revision -> Checklist
Create-Lookup -Table "revision" -TargetTable "checklist" -SchemaName "checklistid" -DisplayName "Checklist"

# Comment -> Checklist
Create-Lookup -Table "comment" -TargetTable "checklist" -SchemaName "checklistid" -DisplayName "Checklist"

# Default Row -> Default Workgroup
Create-Lookup -Table "defaultrow" -TargetTable "defaultworkgroup" -SchemaName "defaultworkgroupid" -DisplayName "Default Workgroup"


Write-Host "`n========================================" -ForegroundColor Green
Write-Host "Provisioning Logic Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host "Note: Changes may take a few moments to appear in the Maker Portal." -ForegroundColor Gray
